src/GestionBundle/Entity/trafico/OrdenServicio.php
<?php

namespace GestionBundle\Entity\trafico;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * OrdenServicio
 *
 * @ORM\Table(name="trafico_orden_servicio")
 * @ORM\Entity(repositoryClass="GestionBundle\Repository\trafico\OrdenServicioRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class OrdenServicio
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fecha", type="date")
     */
    private $fecha;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="salida", type="datetime")
     */
    private $salida;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="llegada", type="datetime")
     */
    private $llegada;

    /**
     * @var bool
     *
     * @ORM\Column(name="activa", type="boolean")
     */
    private $activa = true;

    /**
     * @ORM\ManyToOne(targetEntity="GestionBundle\Entity\trafico\Turno")
     * @ORM\JoinColumn(name="id_turno", referencedColumnName="id")
     * @Assert\NotNull(message="El campo no puede permanecer en blanco")
     */
    private $turno;

    /**
     * @ORM\ManyToOne(targetEntity="GestionBundle\Entity\segVial\Unidad")
     * @ORM\JoinColumn(name="id_unidad", referencedColumnName="id", nullable=true)
     */
    private $unidad;

    /**
     * @ORM\ManyToOne(targetEntity="GestionBundle\Entity\rrhh\Conductor")
     * @ORM\JoinColumn(name="id_conductor_1", referencedColumnName="id", nullable=true)
     */
    private $conductor1;

    /**
     * @ORM\ManyToOne(targetEntity="GestionBundle\Entity\rrhh\Conductor")
     * @ORM\JoinColumn(name="id_conductor_2", referencedColumnName="id", nullable=true)
     */
    private $conductor2;

    /**
     * @ORM\OneToMany(targetEntity="GestionBundle\Entity\comunicacion\OrdenInformada", mappedBy="orden")
     * @ORM\OrderBy({"fecha" = "ASC"})
     */
    private $informadas;

    /**
     * @var bool
     *
     * @ORM\Column(name="finalizada", type="boolean", options={"default": false})
     */
    private $finalizada = false;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="id_usuario_alta", referencedColumnName="id", nullable=true)
     */
    private $userAlta;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="id_usuario_baja", referencedColumnName="id", nullable=true)
     */
    private $userBaja;

    /**
     *
     * @ORM\Column(name="stampAlta", type="integer", nullable=true)
     */
    private $stampAlta;

    /**
     *
     * @ORM\Column(name="stampBaja", type="integer", nullable=true)
     */
    private $stampBaja;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Empresa")
     * @ORM\JoinColumn(name="id_empresa", referencedColumnName="id")
     */
    private $empresa;


    public function updateCreate()
    {
        $fecha = new \DateTime();
        $this->stampAlta = $fecha->getTimestamp();
    }

    public function getUltimaComunicacion()
    {
        return $this->informadas->last();
    }

    public function getOrdenAsArray()
    {
      return array('idServicio' => $this->getTurno()->getId(),
                   'idOrden' =>  $this->id,
                   'idCronograma' => $this->getTurno()->getServicio()->getId(),
                   'Cronograma' => $this->getTurno()->getServicio()->getNombre(),
                   'idCliente' => $this->getTurno()->getServicio()->getCliente()->getId(),
                   'Cliente' => $this->getTurno()->getServicio()->getCliente().'',
                   'Origen' => $this->getTurno()->getServicio()->getOrigen().'',
                   'Destino' => $this->getTurno()->getServicio()->getDestino().'',
                   'Fecha_Servicio' => $this->fecha->format('Y-m-d'),
                   'interno' => $this->getUnidad()->getInterno(),
                   'Horario_Cabecera' => $this->salida->format('H:i:s'),
                   'Horario_Llegada' => $this->salida->format('H:i:s'),
                   'type' => $this->turno->getTipo(),
                   'direction' => $this->turno->getServicio()->getSentido()->getCodigo()
                  );
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set salida
     *
     * @param \DateTime $salida
     *
     * @return OrdenServicio
     */
    public function setSalida($salida)
    {
        $this->salida = $salida;

        return $this;
    }

    /**
     * Get salida
     *
     * @return \DateTime
     */
    public function getSalida()
    {
        return $this->salida;
    }

    /**
     * Set llegada
     *
     * @param \DateTime $llegada
     *
     * @return OrdenServicio
     */
    public function setLlegada($llegada)
    {
        $this->llegada = $llegada;

        return $this;
    }

    /**
     * Get llegada
     *
     * @return \DateTime
     */
    public function getLlegada()
    {
        return $this->llegada;
    }

    /**
     * Set activa
     *
     * @param boolean $activa
     *
     * @return OrdenServicio
     */
    public function setActiva($activa)
    {
        $this->activa = $activa;

        return $this;
    }

    /**
     * Get activa
     *
     * @return bool
     */
    public function getActiva()
    {
        return $this->activa;
    }

    /**
     * Set turno
     *
     * @param \GestionBundle\Entity\trafico\Turno $turno
     *
     * @return OrdenServicio
     */
    public function setTurno(\GestionBundle\Entity\trafico\Turno $turno = null)
    {
        $this->turno = $turno;

        return $this;
    }

    /**
     * Get turno
     *
     * @return \GestionBundle\Entity\trafico\Turno
     */
    public function getTurno()
    {
        return $this->turno;
    }

    /**
     * Set fecha
     *
     * @param \DateTime $fecha
     *
     * @return OrdenServicio
     */
    public function setFecha($fecha)
    {
        $this->fecha = $fecha;

        return $this;
    }

    /**
     * Get fecha
     *
     * @return \DateTime
     */
    public function getFecha()
    {
        return $this->fecha;
    }

    /**
     * Set unidad
     *
     * @param \GestionBundle\Entity\segVial\Unidad $unidad
     *
     * @return OrdenServicio
     */
    public function setUnidad(\GestionBundle\Entity\segVial\Unidad $unidad = null)
    {
        $this->unidad = $unidad;

        return $this;
    }

    /**
     * Get unidad
     *
     * @return \GestionBundle\Entity\segVial\Unidad
     */
    public function getUnidad()
    {
        return $this->unidad;
    }

    /**
     * @Assert\IsTrue(message="La hora de salida no puede ser posterior a la hora de llegada del servicio!")
     */
    public function isHorariosValidos()
    {
        return $this->salida < $this->llegada;
    }

    /**
     * @ORM\PreUpdate
     */
    public function setFechaServicio()
    {
        $this->fecha = $this->salida;
    }

    /**
     * Set conductor1
     *
     * @param \GestionBundle\Entity\rrhh\Conductor $conductor1
     *
     * @return OrdenServicio
     */
    public function setConductor1(\GestionBundle\Entity\rrhh\Conductor $conductor1 = null)
    {
        $this->conductor1 = $conductor1;

        return $this;
    }

    /**
     * Get conductor1
     *
     * @return \GestionBundle\Entity\rrhh\Conductor
     */
    public function getConductor1()
    {
        return $this->conductor1;
    }

    /**
     * Set conductor2
     *
     * @param \GestionBundle\Entity\rrhh\Conductor $conductor2
     *
     * @return OrdenServicio
     */
    public function setConductor2(\GestionBundle\Entity\rrhh\Conductor $conductor2 = null)
    {
        $this->conductor2 = $conductor2;

        return $this;
    }

    /**
     * Get conductor2
     *
     * @return \GestionBundle\Entity\rrhh\Conductor
     */
    public function getConductor2()
    {
        return $this->conductor2;
    }
    /**
     * Constructor
     */
    public function __construct(\AppBundle\Entity\Empresa $empresa)
    {
        $this->empresa = $empresa;
        $this->informadas = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add informada
     *
     * @param \GestionBundle\Entity\comunicacion\OrdenInformada $informada
     *
     * @return OrdenServicio
     */
    public function addInformada(\GestionBundle\Entity\comunicacion\OrdenInformada $informada)
    {
        $this->informadas[] = $informada;

        return $this;
    }

    /**
     * Remove informada
     *
     * @param \GestionBundle\Entity\comunicacion\OrdenInformada $informada
     */
    public function removeInformada(\GestionBundle\Entity\comunicacion\OrdenInformada $informada)
    {
        $this->informadas->removeElement($informada);
    }

    /**
     * Get informadas
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getInformadas()
    {
        return $this->informadas;
    }

    /**
     * Set finalizada
     *
     * @param boolean $finalizada
     *
     * @return OrdenServicio
     */
    public function setFinalizada($finalizada)
    {
        $this->finalizada = $finalizada;

        return $this;
    }

    /**
     * Get finalizada
     *
     * @return boolean
     */
    public function getFinalizada()
    {
        return $this->finalizada;
    }

    /**
     * Set stampAlta
     *
     * @param integer $stampAlta
     *
     * @return OrdenServicio
     */
    public function setStampAlta($stampAlta)
    {
        $this->stampAlta = $stampAlta;

        return $this;
    }

    /**
     * Get stampAlta
     *
     * @return integer
     */
    public function getStampAlta()
    {
        return $this->stampAlta;
    }

    /**
     * Set userAlta
     *
     * @param \AppBundle\Entity\Usuario $userAlta
     *

src/GestionBundle/Entity/trafico/opciones/FrecuenciaServicio.php
<?php

namespace GestionBundle\Entity\trafico\opciones;

use Doctrine\ORM\Mapping as ORM;

/**
 * FrecuenciaServicio
 *
 * @ORM\Table(name="trafico_opciones_frecuencia_servicio")
 * @ORM\Entity(repositoryClass="GestionBundle\Repository\trafico\opciones\FrecuenciaServicioRepository")
 */

////////////////Regular - Temporario - Eventual
class FrecuenciaServicio
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="frecuencia", type="string", length=255, unique=true)
     */
    private $frecuencia;
    

    public function __toString()
    {
        return strtoupper($this->frecuencia);
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set frecuencia
     *
     * @param string $frecuencia
     *
     * @return FrecuenciaServicio
     */
    public function setFrecuencia($frecuencia)
    {
        $this->frecuencia = $frecuencia;

        return $this;
    }

    /**
     * Get frecuencia
     *
     * @return string
     */
    public function getFrecuencia()
    {
        return $this->frecuencia;
    }
}

src/GestionBundle/Form/trafico/OrdenServicioType.php
<?php

namespace GestionBundle\Form\trafico;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class OrdenServicioType extends AbstractType
{
    
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $empresa = $options['empresa'];
        $builder->add('salida', DateTimeType::class, ['widget' => 'single_text'])
                ->add('llegada', DateTimeType::class, ['widget' => 'single_text'])
                ->add('activa')                
                ->add('guardar', SubmitType::class, ['label' => 'Modificar'])
                ->add('unidad',
                      EntityType::class, 
                      [
                      'class' => 'GestionBundle:segVial\Unidad',
                      'query_builder' => function (EntityRepository $er) use ($empresa){
                                                                                        return $er->createQueryBuilder('u')
                                                                                                  ->where('u.empresa = :empresa')
                                                                                                  ->andWhere('u.activo = :activo')
                                                                                                  ->setParameter('empresa', $empresa)
                                                                                                  ->setParameter('activo', true)
                                                                                                  ->orderBy('u.interno', 'ASC');
                       },
                       'required' => false
                      ]
                    )
                ->add('conductor1',
                      EntityType::class, 
                      [
                      'class' => 'GestionBundle:rrhh\Conductor',
                      'query_builder' => function (EntityRepository $er) use ($empresa){
                                                                                        return $er->createQueryBuilder('u')
                                                                                                  ->where('u.empresa = :empresa')
                                                                                                  ->andWhere('u.activo = :activo')
                                                                                                  ->setParameter('empresa', $empresa)
                                                                                                  ->setParameter('activo', true)
                                                                                                  ->orderBy('u.apellido', 'ASC');
                       },
                       'required' => false
                      ]
                    )
                ->add('conductor2',
                      EntityType::class, 
                      [
                      'class' => 'GestionBundle:rrhh\Conductor',
                      'query_builder' => function (EntityRepository $er) use ($empresa){
                                                                                        return $er->createQueryBuilder('u')
                                                                                                  ->where('u.empresa = :empresa')
                                                                                                  ->andWhere('u.activo = :activo')
                                                                                                  ->setParameter('empresa', $empresa)
                                                                                                  ->setParameter('activo', true)
                                                                                                  ->orderBy('u.apellido', 'ASC');
                       },
                       'required' => false
                      ]
                    )
                ->addEventListener(
                                    FormEvents::PRE_SET_DATA,
                                    [$this, 'onPreSetData']
                );
    }

    public function onPreSetData(FormEvent $event)
    {
        $orden = $event->getData();
        $form = $event->getForm();
        $form->add('cliente', EntityType::class, ['class' => 'GestionBundle:ventas\Cliente', 'mapped' => false, 'choices' => [$orden->getTurno()->getServicio()->getCliente()]])
             ->add('turno', EntityType::class, ['class' => 'GestionBundle:trafico\Turno', 'choice_label' => 'vistaDiagrama', 'choices' => [$orden->getTurno()]]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'GestionBundle\Entity\trafico\OrdenServicio'
        ))
        ->setRequired('empresa');

    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'gestionbundle_trafico_ordenservicio';
    }


}

src/GestionBundle/Form/trafico/opciones/TurnoClienteType.php
<?php

namespace GestionBundle\Form\trafico\opciones;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TurnoClienteType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('turno')->add('empresa');
    }/**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'GestionBundle\Entity\trafico\opciones\TurnoCliente'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'gestionbundle_trafico_opciones_turnocliente';
    }


}

src/GestionBundle/Resources/views/trafico/altaOrdenServicio.html.twig
{% extends '@App/base.html.twig' %}

{% block content %}

	<div class="h5 mt-5 mb-3">Diagramar Servicio</div>

    <hr>
    {% include '@Gestion/messages.html.twig'  %}
    {{ form_start(form, {'attr' : {'novalidate' : 'novalidate', 'class' : 'border border-light'}}) }}
	    <div class='form-row ml-4 mr-2 mt-2'>	 
	    	<div class=' col-lg-4 col-sm-12'>
			    {{ form_label(form.fecha) }}
			    {{ form_widget(form.fecha, { 'attr' : {'class' : 'form-control form-control-sm text-uppercase'}}) }}
			    {{ form_errors(form.fecha) }}
			</div>
	    	<div class=' col-lg-8 col-sm-12'>
			    {{ form_label(form.turno) }}
			    {{ form_widget(form.turno, { 'attr' : {'class' : 'form-control form-control-sm text-uppercase'}}) }}
			    <div class="text-danger">{{ form_errors(form.turno) }}</div>
			</div>
		</div>
		<div class='form-row ml-4 mr-2 mt-2 align-right'>
			{{ form_widget(form.diagramar, { 'attr' : {'class' : 'btn btn-sm btn-default'}}) }}
		</div>
    {{ form_end(form) }}

    {% if ordenes is defined %}
	    <div class="h5 mt-5 mb-3">Servicios diagramados para el : {{ fecha|date('d/m/Y') }}</div>
		<table class="table table-hover table-bordered table-striped table-sm mt-2">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Cliente</th>
		      <th scope="col">Servicio</th>
		      <th scope="col">Hora Salida</th>
		      <th scope="col">Hora Llegada</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for o in ordenes %}
		  		<tr>
		  			<td>{{ loop.index }}</td>
		  			<td>{{ o.turno.servicio.cliente|upper }}</td>
		  			<td>{{ o.turno.servicio|upper }}</td>
		  			<td>{{ o.salida|date('d/m/Y - H:i') }}</td>
		  			<td>{{ o.llegada|date('d/m/Y - H:i') }}</td>
		  		</tr>
		  	{% endfor %}
		  </tbody>
		</table>
		<a class="btn btn-sm btn-default" href="{{ path('listado_servicios') }}">Volver</a>
	{% endif %}
{% endblock %}

{% block javascripts %}

<script type="text/javascript">


</script>
{% endblock %}

src/GestionBundle/Resources/views/trafico/altaServicio.html.twig
{% extends '@App/base.html.twig' %}

{% block content %}
    <div class="h3 mt-5 mb-3">{{ label }} Servicio</div>
    <hr>
    {% include '@Gestion/messages.html.twig'  %}
    {{ form_start(form, {'attr' : {'novalidate' : 'novalidate', 'class' : 'border border-light'}}) }}
	    <div class='form-row ml-4 mr-2 mt-2'>	 
	    	<div class=' col-lg-4 col-sm-12'>
			    {{ form_label(form.cliente) }}
			    {{ form_widget(form.cliente, { 'attr' : {'class' : 'form-control form-control-sm text-uppercase'}}) }}
			    {{ form_errors(form.cliente) }}
			</div>
	    	<div class=' col-lg-4 col-sm-12'>
			    {{ form_label(form.nombre) }}
			    {{ form_widget(form.nombre, { 'attr' : {'class' : 'form-control text-uppercase form-control-sm'}}) }}
			    <div class="text-danger">{{ form_errors(form.nombre) }}</div>
			</div>
	    	<div class=' col-lg-2 col-sm-12'>
			    {{ form_label(form.kmRecorrido) }}
			    {{ form_widget(form.kmRecorrido, { 'attr' : {'class' : 'form-control text-uppercase form-control-sm'}}) }}
			    <div class="text-danger">{{ form_errors(form.kmRecorrido) }}</div>
			</div>
		</div>
	    <div class='form-row ml-4 mr-2 mt-2'>	 
	    	<div class=' col-lg-4 col-sm-12'>
			    {{ form_label(form.sentido) }}
			    {{ form_widget(form.sentido, { 'attr' : {'class' : 'form-control form-control-sm text-uppercase'}}) }}
			    <div class="text-danger">{{ form_errors(form.sentido) }}</div>
			</div>
	    	<div class=' col-lg-4 col-sm-12'>
			    {{ form_label(form.tipoServicio) }}
			    {{ form_widget(form.tipoServicio, { 'attr' : {'class' : 'form-control form-control-sm text-uppercase'}}) }}
			    <div class="text-danger">{{ form_errors(form.tipoServicio) }}</div>
			</div>			
		</div>
	    <div class='form-row ml-4 mr-2 mt-2'>	    
	    	<div class=' col-lg-4 col-sm-12'>
			    {{ form_label(form.origen) }}
			    {{ form_widget(form.origen, { 'attr' : {'class' : 'form-control form-control-sm text-uppercase'}}) }}
			    <div class="text-danger">{{ form_errors(form.origen) }}</div>
			</div>    
	    	<div class=' col-lg-4 col-sm-12'>
			    {{ form_label(form.destino) }}
			    {{ form_widget(form.destino, { 'attr' : {'class' : 'form-control form-control-sm text-uppercase'}}) }}
			    <div class="text-danger">{{ form_errors(form.destino) }}</div>
			</div>
		</div>
		{% if form.activo is defined %}
		    <div class='form-row ml-4 mr-2 mt-2'>	    
		    	<div class=' col-lg-4 col-sm-12'>
				    {{ form_label(form.activo) }}
				    {{ form_widget(form.activo) }}
				</div>    
			</div>
		{% endif %}
		<div class='form-row ml-4 mr-2 mt-2 align-right'>
			{{ form_widget(form.guardar, { 'attr' : {'class' : 'btn btn-success'}}) }}
		</div>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}

<script type="text/javascript">


</script>
{% endblock %}

src/GestionBundle/Resources/views/trafico/comunicarServicios.html.twig
{% extends '@App/base.html.twig' %}

{% block content %}
	<div class="h5 mt-5 mb-3">Comunicar Servicios</div>
    {{ form_start(form, {'attr' : {'novalidate' : 'novalidate', 'class' : 'border border-light'}}) }}
	    <div class='form-row ml-4 mr-2 mt-2'>	 
	    	<div class=' col-lg-4 col-sm-12'>
			    {{ form_label(form.fecha) }}
			    {{ form_widget(form.fecha, { 'attr' : {'class' : 'form-control form-control-sm text-uppercase'}}) }}
			    {{ form_errors(form.fecha) }}
			</div>
		</div>
		<div class='form-row ml-4 mr-2 mt-2 align-right'>
			{{ form_widget(form.diagramar, { 'attr' : {'class' : 'btn btn-sm btn-default'}}) }}
		</div>
    {{ form_end(form) }}

    <hr>
    {% include '@Gestion/messages.html.twig'  %}
    {% if ordenes is defined %}
	    <div class="h5 mt-2 mb-3">Servicios diagramados para el : {{ fecha|date('d/m/Y') }}</div>
		<table class="table table-hover table-bordered table-striped table-sm mt-2">
		  <thead>
		    <tr>
		      <th scope="col">Cliente</th>
		      <th scope="col">Servicio</th>
		      <th scope="col">Hora Salida</th>
		      <th scope="col">Hora Llegada</th>
		       <th scope="col">Unidad</th>
		       <th scope="col">Conductor</th>
		       <th scope="col">Estado</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for o in ordenes %}
		  		<tr data-id="{{ o.id }}">
		  			<td>{{ o.turno.servicio.cliente|upper }}</td>
		  			<td>{{ o.turno.servicio|upper }}</td>
		  			<td>{{ o.salida|date('d/m/Y - H:i') }}</td>
		  			<td>{{ o.llegada|date('d/m/Y - H:i') }}</td>
		  			<td class="text-right">{{ o.unidad }}</td>
		  			<td>{{ o.conductor1 }}</td>
		  			<td id="{{ o.id }}" class="status">
		  				{% if o.UltimaComunicacion %}
		  					{% if o.ultimaComunicacion.status %}
		  						<i class="far fa-check-circle fa-2x" title="Ultima comunicacion: {{ o.ultimaComunicacion.fecha|date('d/m/Y - H:i:s')}}"></i>
		  					{% else %}
		  						<i class="far fa-times-circle fa-2x" title="Ultima comunicacion: {{ o.ultimaComunicacion.fecha|date('d/m/Y - H:i:s')}} - Error: {{ o.ultimaComunicacion.mensajeRespuesta }}"></i>
		  					{% endif %}
		  				{% else %}
		  					<i class="far fa-times-circle fa-2x" title="No se ha realizado aun ninguna comunicacion"></i>
		  				{% endif %}

		  			</td>
		  		</tr>
		  	{% endfor %}
		  </tbody>
		</table>
		<input type="button" class="btn btn-default" id="btnsnd" value="Comunicar informacion"/>
	{% endif %}
{% endblock %}

{% block javascripts %}

<script type="text/javascript">

$(document).ready(function() {
				$("#btnsnd").click(function(){	
												var path = "{{ path('comunicar_orden_servicio', { id : 'IDORDEN' }) }}";
												bootbox.confirm({
												    title: "Enviar informacion?",
												    message: "Seguro enviar la informacion de los servicios diagramados?",
												    buttons: {
												        cancel: {
												            label: '<i class="fa fa-times"></i> Cancelar'
												        },
												        confirm: {
												            label: '<i class="fa fa-check"></i> Confirmar'
												        }
												    },
												    callback: function (result) {
														if (result)
													    {
													    	$(".status").html('<i class="fas fa-spinner fa-spin fa-2x"></i>');
													    	$( ".status" ).each(function() {
													    									var td = $(this);
													    									var pathc = path.replace('IDORDEN', td.attr('id'));
													    									$.post(pathc,
													    										   function(data)
													    										   {
													    										   		if (data.error)
													    										   		{
													    										   			td.html('<i title="'+data.message+'" class="far fa-times-circle fa-2x"></i>');
													    										   		}
													    										   		else
													    										   		{
													    										   			td.html('<i class="far fa-check-circle fa-2x"></i>');
													    										   		}
													    										   });
																						  
																						});
													    } 

												    }
												});															

				});
															

});

</script>
{% endblock %}